from django.db.models.signals import post_migrate
from django.dispatch import receiver
from .models import Curso, Departamento, Interesse, Lab

@receiver(post_migrate)
def create_default_departments(sender, **kwargs):
    if sender.name == 'icfinder_app':
        if not Curso.objects.exists():
            cursos_array = ['Engenharia Ambiental', 'Engenharia Civil', 'Engenharia de Computação', 
                            'Engenharia de Materiais', 'Engenharia de Minas', 'Engenharia de Petróleo',
                            'Engenharia de Produção', 'Engenharia Elétrica, ênfase em Automação e Controle', 
                            'Engenharia Elétrica, ênfase em Energia e Automação', 'Engenharia Elétrica, ênfase em Telecomunicações', 
                            'Engenharia Elétrica, ênfase em Sistemas Eletrônicos', 'Engenharia Mecânica',
                            'Engenharia Mecatrônica', 'Engenharia Metalúrgica',
                            'Engenharia Naval', 'Engenharia Química ']
            for curso in cursos_array:
                Curso.objects.create(curso=curso)
        if not Departamento.objects.exists():
            departamentos_array = ["PCC - Construção Civil", "PMT - Metalúrgica e de Materiais",
                                    "PCS - Computação e Sistemas Digitais", "PNV - Naval e Oceânica",
                                    "PEA - Energia e Automação Elétricas", "PQI - Química",
                                    "PEF - Estruturas e Geotécnica", "PRO - Produção",
                                    "PHA - Hidráulica e Ambiental", "PSI - Sistemas Eletrônicos",
                                    "PME - Mecânica",  "PTC - Telecomunicações e Controle",
                                    "PMI - de Minas e de Petróleo", "PTR - Transportes",
                                    "PMR - Mecatrônica e Sist. Mecânicos"]
            for departamento in departamentos_array:
                Departamento.objects.create(departamento=departamento)
        if not Interesse.objects.exists():
            interesses_array = ['Saúde', 'Programação', 'Automação', 'Robótica',
                                'Construção', 'Otmização de processos', 'Matemática',
                                'Análise de dados', 'Hardware', 'Meio ambiente',
                                'Materiais', 'Energia', 'Inteligência artificial',
                                'IoT', 'Finanças']
            for interesse in interesses_array:
                Interesse.objects.create(interesse=interesse)
        if not Lab.objects.exists():
            nomes_lab_array = ['Laboratório de Ensino de CAD',
                                'Laboratório de Ensino Experimental',
                                'Laboratório de Materiais, Componentes e Processos Construtivos',
                                'Laboratório de Microbiologia do Ambiente Construído',
                                'Laboratório de Microestrutura e Ecoeficiência de Materiais',
                                'Laboratório de Projeto Auxiliado por Computador',
                                'Laboratório de Sistemas Prediais',
                                'Laboratório de Soluções Baseadas na Natureza',
                                'Laboratório Didático de Prototipação',
                                'Laboratório de Análise de Segurança',
                                'Laboratório de Arquitetura de Redes de Computadores',
                                'Laboratório de Arquitetura e Computação de Alto Desempenho',
                                'Laboratório de Automação Agrícola',
                                'Laboratório de Engenharia de Conhecimento',
                                'Laboratório de Linguagem e Técnicas Adaptativas',
                                'Laboratório de Microprocessadores',
                                'Laboratório de Programação',
                                'Laboratório de Sistemas Aberto/Smart',
                                'Laboratório de Sistemas Complexos',
                                'Laboratório de Sistemas Digitais',
                                'Laboratório de Software',
                                'Laboratório de Sustentabilidade',
                                'Laboratório de Técnicas Inteligentes',
                                'Laboratório de Tecnologia em Software',
                                'Laboratório de Tecnologias Interativas',
                                'Núcleo de Pesquisa em Biodiversidade e Computação',
                                'Centro de Estudos em Regulação e Qualidade de Energia',
                                'Grupo de Energia',
                                'Grupo de Máquinas Elétricas e Acionamentos',
                                'Grupo de Automação Elétrica em Sistemas Industriais',
                                'Laboratório de Eletromagnetismo Aplicado',
                                'Laboratório de Eletrônica e Potência',
                                'Laboratório de Pesquisa em Automação e Proteção de Sistemas Elétricos - LPROT',
                                'Laboratório de Sensores Ópticos',
                                'Laboratório de Sistemas de Potência',
                                'Laboratório de Estruturas e Materiais Estruturais',
                                'Laboratório de Mecânica Computacional',
                                'Laboratório de Mecânica dos Solos',
                                'Centro Internacional de Referência em Reúso de Água',
                                'Laboratório Analítico e Experimental de Resíduos Sólidos Industriais e Urbanos',
                                'Laboratório de Hidráulica',
                                'Laboratório de Saneamento',
                                'Laboratório de Sistemas de Suporte de Decisão',
                                'Centro de Automação e Tecnologia do Projeto',
                                'Centro de Engenharia Automotiva',
                                'Grupo de Pesquisa em Refrigeração, Ar Condicionado e Conforto Térmico',
                                'Laboratório de Acústica e Meio Ambiente',
                                'Laboratório de Dinâmica e Controle',
                                'Laboratório de Dinâmica e Simulação Veicular',
                                'Laboratório de Engenharia Ambiental e Biomédica',
                                'Laboratório de Engenharia do Vento',
                                'Laboratório de Engenharia Térmica e Ambiental',
                                'Laboratório de Estudos da Qualidade do Ar Interior',
                                'Laboratório de Fenômenos de Superfícies',
                                'Laboratório de Mecânica Offshore',
                                'Laboratório de Sistemas Energéticos Alternativos',
                                'Núcleo de Dinâmica e Fluidos',
                                'Integrações Tecnológicas em Análises de Rochas e Fluidos',
                                'Laboratório de Amostragem e Manuseio de Sólidos Granulados',
                                'Laboratório de Caracterização Tecnológica',
                                'Laboratório de Controle Ambiental, Higiene e Segurança na Mineração',
                                'Laboratório de Engenharia de Petróleo',
                                'Engenharia Mineral',
                                'Laboratório de Mecânica de Rochas',
                                'Laboratório de Planejamento e Otimização de Lavra',
                                'Laboratório de Prototipagem Rápida',
                                'Laboratório de Simulação e Controle de Processos de Tratamento de Minérios',
                                'Laboratório de Simulação e Gerenciamento de Reservatórios de Petróleo',
                                'Laboratório de Tratamento de Minérios e Resíduos Industriais',
                                'Laboratório Integrado de Simulação Tecnológica',
                                'Núcleo de Pesquisa para a Pequena Mineração Responsável',
                                'Laboratório de Análise de Confiabilidade',
                                'Laboratório de Design',
                                'Laboratório de Engenharia de Fabricação',
                                'Laboratório de Fenômenos de Superfícies',
                                'Laboratório de Geometria Computacional',
                                'Laboratório de Impacto em Estruturas',
                                'Laboratório de Mecanismos, Máquinas e Robôs',
                                'Laboratório de Otimização de Sistemas Multifísicos',
                                'Laboratório de Percepção Avançada',
                                'Laboratório de Robôs Sociáveis',
                                'Laboratório de Sensores e Atuadores',
                                'Laboratório de Sistemas de Automação',
                                'Laboratório de Sistemas Embarcados',
                                'Laboratório de Sistemas Mecatrônicos de Precisão',
                                'Laboratório de Tomada de Decisão',
                                'Laboratório de Ultrassom',
                                'Laboratório de Veículos não Tripulados',
                                'Tanque de Provas Numérico',
                                'Central Multiusuário do Grupo de Pesquisa em Soldagem e Junção – CM',
                                'Hall Tecnológico “Prof. Dr. Carlos Dias Brosch”',
                                'Laboratório de Argilas',
                                'Laboratório de Auto Redução e Fusão Redução',
                                'Laboratório de Caracterização Microestrutural Hubertus Colpaert',
                                'Laboratório de Computação em Ciência dos Materiais',
                                'Laboratório de Engenharia de Macromoléculas',
                                'Laboratório de Matérias Primas Particuladas e Sólidos não Metálicos',
                                'Laboratório de Moagem de Alta Energia, Materiais de Carbono e Compósitos',
                                'Laboratório de Processos Cerâmicos',
                                'Laboratório de Processos Eletroquímicos',
                                'Laboratório de Reologia e Engenharia de Polímeros',
                                'Laboratório de Simulação em Engenharia de Materiais',
                                'Laboratório de Solidificação e Fundição',
                                'Laboratório de Transformação de Fases',
                                'Centro de Inovação em Logística e Infra',
                                'Laboratório de análise, avaliação e gerenciamento de riscos',
                                'Laboratório de Engenharia Naval e Oceânica',
                                'Laboratório de Modelos',
                                'Laboratório de Otimização e Projeto Integrado',
                                'Laboratory for Numeral Methods in Engineering: Research, Application and Learning',
                                'Núcleo Avançado em Mecânica da Fratura e Integridade Estrutural',
                                'Centro de Capacitação e Pesquisa em Meio Ambiente',
                                'Grupo de Engenharia de Bioprocessos',
                                'Grupo de Pesquisa em Processos Oxidativos Avançados',
                                'Grupo de Prevenção da Poluição',
                                'Laboratório de Eletroquímica e Corrosão',
                                'Laboratório de Engenharia de Alimentos',
                                'Laboratório de Espectrometria de Massa',
                                'Laboratório de Pesquisa e Inovação em Processos Catalíticos',
                                'Centro de Inovação em Sistemas Logísticos',
                                'Grupo de Estudos de Modelagem no Setor de Energia',
                                'Laboratório de Análise, Desenvolvimento e Operação de Sistemas',
                                'Laboratório de Cidades, Tecnologia e Urbanismo',
                                'Laboratório de Estratégias Integradas da Indústria da Mobilidade',
                                'Laboratório de Estudos em Design de Serviços e em Sustentabilidade',
                                'Laboratório de Gestão da Inovação',
                                'Laboratório de Gestão de Projetos',
                                'Inteligência Competitiva',
                                'Laboratório de Projeto e Engenharia do Trabalho',
                                'Núcleo de Apoio à Pesquisa Observatório da Inovação e Competitividade',
                                'Redes de Cooperação e Gestão do Conhecimento',
                                'InovaLab',
                                'Laboratório de Microeletrônica',
                                'Laboratório de Processamento de Sinais',
                                'Laboratório de Sistemas Integráveis',
                                'Laboratório de Automação e Controle',
                                'Laboratório de Comunicações e Sinais',
                                'Laboratório de Controle de Processos Industriais',
                                'Laboratório de Engenharia Biomédica',
                                'Laboratório de Estudos Metodológicos de Tráfego e Transportes',
                                'Laboratório de Inovação em Vias Metroferroviárias',
                                'Laboratório de Mecânica de Pavimentos',
                                'Laboratório de Modelagem e Algoritmos em Transportes e Logística',
                                'Laboratório de Planejamento e Operação de Transportes',
                                'Laboratório de Tecnologia de Informação em Transportes',
                                'Laboratório de Tecnologia de Pavimentação',
                                'Laboratório de Topografia e Geodésia']
            siglas_lab_array = ['LEC',
                                'LEExp',
                                'LMCP',
                                'LMAC',
                                'LME',
                                'LabCAD',
                                'LSP',
                                'LSBN',
                                'LDP',
                                'GAS',
                                'LARC',
                                'LAHPC',
                                'LAA',
                                'KNOMA',
                                'LTA',
                                'LABPROC',
                                'LABPROG',
                                'LSA',
                                'GSC',
                                'LABDIGI',
                                'LABSOFT',
                                'LASSU',
                                'LTI',
                                'LTS',
                                'Interlab',
                                'BIOCOMP',
                                'ENERQ',
                                'GEPEA',
                                'GMAcq',
                                'GAESI',
                                'LMAG',
                                'LEP',
                                'Laboratório de Redes Elétricas Avançadas - LGrid',
                                'LSO',
                                'LSP',
                                'LEM',
                                'LMC',
                                'LMS',
                                'CIRRA',
                                'LAERSIU',
                                'CTH',
                                'LabSan',
                                'LabSid',
                                'CAETEC',
                                'CEA',
                                'GREAC',
                                'LACMAM',
                                'LDC',
                                'LDSV',
                                'LAB',
                                'LEVE',
                                'LETE',
                                'LEQAI',
                                'LFS',
                                'LMO',
                                'SISEA',
                                'NDF',
                                'InTRA',
                                'LAM',
                                'LCT',
                                'LACASEMIN',
                                'LEP',
                                'LFQI',
                                'LMR',
                                'LAPOL',
                                'TriLAB',
                                'LSC',
                                'LASG',
                                'LTM',
                                'LISTEC',
                                'NAP-Mineração',
                                'ReLab',
                                'D-Lab',
                                'LEFA',
                                'LFS',
                                'LGC',
                                'GMSIE',
                                'LaMMaR',
                                'MSOL',
                                'LPA',
                                'LRS',
                                'LSAT',
                                'LSA',
                                'ESL',
                                'MPREC',
                                'LTD',
                                'LUS',
                                'LVNT',
                                'TPN-USP',
                                'GPSJ',
                                'HallTec',
                                'LARG',
                                'LABRED',
                                'LCMHC',
                                'LCCMat',
                                'LEM',
                                'LMPSol',
                                'LM²C²',
                                'LPC',
                                'LPE',
                                'LabPol',
                                'LSEM',
                                'LSF',
                                'LTF',
                                'Estrutura Portuária - CILIP',
                                'LabRisco',
                                'LENO',
                                'LabModelos',
                                'Loopin',
                                'LabNUMERAL',
                                'NAMEF',
                                'CEPEMA',
                                'GEnBio',
                                'AdOx',
                                'GP2',
                                'LEC',
                                'LEA',
                                'Dempster',
                                'LaPCat',
                                'CISLog',
                                'GEMSE',
                                'LADOS',
                                'CONECTICIDADE/LCTU',
                                'Mobilab',
                                'LEDss',
                                'LGI',
                                'LGP',
                                'LETICIC',
                                'LPET',
                                'NAP-OIC',
                                'REDECOOP',
                                'Elétrica',
                                'LME',
                                'LPS',
                                'LSI',
                                'LAC',
                                'LCS',
                                'LCPI',
                                'LEB',
                                'LEMT',
                                'LIM',
                                'LMP',
                                'LMAT',
                                'LPT',
                                'LTIT',
                                'LTP',
                                'LTG']
            for i in range(len(nomes_lab_array)):
                Lab.objects.create(sigla=siglas_lab_array[i], nomeCompleto=nomes_lab_array[i])